import * as $protobuf from "protobufjs";
/** AnimalRandomMsgDefine enum. */
export enum AnimalRandomMsgDefine {
    MSG_PUSH_ROOM_INFO = 9500,
    MSG_REQ_ADDCHIP = 9501,
    MSG_PUSH_Animal_BET_INFO = 9512,
    MSG_REQ_BE_BANKER = 9502,
    MSG_PUSH_STEP_INFO = 9503,
    MSG_PUSH_BANKER_CHANGE = 9505,
    MSG_PUSH_Animal_PLAYER_LEAVE = 9506,
    MSG_PUSH_CLEARING_INFO = 9507,
    MSG_REQ_QUIT_BANKERQUIT = 9508,
    MSG_PUSH_KIT_OUT_ROOM = 9509,
    MSG_REQ_ONLINE_PLAYER_INFO = 9510,
    MSG_REQ_WANT_TO_BANKER_INFO = 9511,
    MSG_REQ_Multi_ADDCHIP = 9513,
    MSG_REQ_LEAVE_ROOM = 9504,
    MSG_GAME_LOGIN_ANIMAL = 9514,
    MSG_COMMON_RANK_LIST = 9515
}
