import * as $protobuf from "protobufjs";
/** DouDiZhuMsgDefine enum. */
export enum DouDiZhuMsgDefine {
    MSG_PUSH_DOUDIZHU_INIT = 8900,
    MSG_PUSH_HANDCARD = 8901,
    MSG_PUSH_COUNT_DOWN = 8902,
    MSG_REQUEST_ACTION = 8903,
    MSG_PUSH_FINAL_LANDLORD_INFO = 8904,
    MSG_PUSH_SETTLEMENT_INFO = 8905,
    MSG_KICK_OUT_ROOM = 8906,
    MSG_PUSH_ACTION = 8907,
    MSG_PUSH_REJOIN_INFO = 8908,
    MSG_REQUST_REFRESH_THREECARD = 8911,
    MSG_GAME_LOGIN_DOU_DI_ZHU = 8909,
    MSG_GAME_LOGOUT_DOU_DI_ZHU = 8910
}
